# Site settings
title:       Kalkin7's Test Site
email:       kalkin7@gmail.com
author:      Kalkin7
description: "Pixyll Jekyll Theme Test Blog."
baseurl:     ""
url:         "http://blogtest01.kalkinblog.tk"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username: kalkin_7
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
