# Site settings
title: kalkin7
email: kalkin7@gmail.com
author: Karl Hong
description: "나의 테스트용 블로그"
baseurl: ""
url: "http://www.kkwiki.tk/"
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
sass:
  compressed: true

