# Site settings
title: kalkin7
email: your_email@example.com
author: Karl Hong
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl: ""
url: "http://www.kkwiki.tk/"
google_analytics:
animated: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
sass:
  compressed: true

